# Generated by Django 4.2.5 on 2023-09-06 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('reg_end_dt', models.DateTimeField()),
                ('e_start_dt', models.DateTimeField()),
                ('e_end_dt', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=100)),
                ('candidates', models.ManyToManyField(blank=True, to='candidate.candidate')),
                ('voters', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
