# Generated by Django 4.2.5 on 2023-09-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_std_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='std_id',
            field=models.IntegerField(null=True),
        ),
    ]
