# Generated by Django 4.2.5 on 2023-09-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_std_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='voter_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
